// packages/sdk-lit/src/index.ts
import type { ReactiveController, ReactiveControllerHost } from 'lit';
import { connectPlugin } from '../../sdk/src/index.ts';
import type { PluginClient } from '../../sdk/src/index.ts';

export class PluginConnection implements ReactiveController {
  client: PluginClient | null = null;
  error = '';
  navigation:string|null=null;
  private generation = 0;
  constructor(private host: ReactiveControllerHost) { host.addController(this); }
  hostConnected(): void {
    const generation = ++this.generation;
    void connectPlugin().then(client => {
      if (generation !== this.generation) { client.dispose(); return; }
      this.client = client;
      client.subscribe(event=>{
        if(typeof event!=='object'||event===null||!('type' in event))return;
        if(event.type==='host.navigation'&&'route' in event&&typeof event.route==='string'&&/^[a-z0-9/-]{1,120}$/.test(event.route)){this.navigation=event.route;this.host.requestUpdate();return;}
        if(event.type!=='host.context')return;
        if('theme' in event&&(event.theme==='light'||event.theme==='dark'||event.theme==='system'))document.documentElement.dataset.theme=event.theme;
        if('textScale' in event&&typeof event.textScale==='number'&&event.textScale>=1&&event.textScale<=2){document.documentElement.style.fontSize=`${16*event.textScale}px`;document.documentElement.style.setProperty('--text-scale',String(event.textScale));}
      });
      this.host.requestUpdate();
    }).catch(reason => { this.error = reason instanceof Error ? reason.message : 'Connection failed'; this.host.requestUpdate(); });
  }
  hostDisconnected(): void { this.generation++; this.client?.dispose(); this.client = null; }
}

// packages/sdk-react/src/index.ts
import { useEffect, useState } from 'react';
import { connectPlugin } from '../../sdk/src/index.ts';
import type { PluginClient } from '../../sdk/src/index.ts';
import { z } from 'zod';
const contextSchema=z.object({type:z.literal('host.context'),theme:z.enum(['system','light','dark']).optional(),textScale:z.number().min(1).max(2).optional(),models:z.array(z.strictObject({slug:z.string().max(240),displayName:z.string().max(240)})).max(100).optional()}).passthrough();
export type HostContext=z.infer<typeof contextSchema>;

export function usePluginClient(): { client: PluginClient | null; error: string; context:HostContext|null;navigation:string|null } {
  const [client, setClient] = useState<PluginClient | null>(null);
  const [error, setError] = useState('');
  const [context,setContext]=useState<HostContext|null>(null);
  const [navigation,setNavigation]=useState<string|null>(null);
  useEffect(() => {
    let stopped = false;
    let connection: PluginClient | null = null;
    void connectPlugin().then(value => {
      connection = value;
      if (stopped) value.dispose(); else {
        value.subscribe(event=>{
          const route=z.strictObject({type:z.literal('host.navigation'),route:z.string().regex(/^[a-z0-9/-]{1,120}$/)}).safeParse(event);if(route.success){setNavigation(route.data.route);return;}
          const parsed=contextSchema.safeParse(event);if(!parsed.success)return;
          const data=parsed.data;setContext(data);
          if(data.theme)document.documentElement.dataset.theme=data.theme;
          if(data.textScale){document.documentElement.style.fontSize=`${16*data.textScale}px`;document.documentElement.style.setProperty('--text-scale',String(data.textScale));}
        });
        setClient(value);
      }
    }).catch(reason => { if (!stopped) setError(reason instanceof Error ? reason.message : 'Connection failed'); });
    return () => { stopped = true; connection?.dispose(); };
  }, []);
  return { client, error, context,navigation };
}
